{
  "version": "3.4",
  "services": {
    "weaviate": {
      "image": "semitechnologies/weaviate:1.23.0",
      "ports": [
        "8080:8080"
      ],
      "restart": "on-failure:0",
      "environment": {
        "QUERY_DEFAULTS_LIMIT": "25",
        "AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED": "true",
        "DEFAULT_VECTORIZER_MODULE": "none",
        "CLUSTER_HOSTNAME": "node1",
        "PERSISTENCE_DATA_PATH": "/var/lib/weaviate",
        "ENABLE_MODULES": ""
      },
      "volumes": [
        "weaviate_data:/var/lib/weaviate"
      ]
    }
  },
  "volumes": {
    "weaviate_data": {}
  }
}
